### ISSUE TITLE
Issue 1:1 SBR-sunSBR

### ISSUE THREAD

**Issue by Crypturco** [saber-hq/governance#11]
Hey everyone,

Sunny is a DeFi yield aggregator built on top of Saber, and its main purpose was to build value around Saber Ecosystem with Saber wars, so everyone who believed  in Saber team and Saber Ecosystem locked their SBR tokens in Sunny(yiSunSBR) for sunSBR (mostly retail, -%95 loss). Unfortunately nothing is going on as planned in time of locks so i am proposing that the DAO should issue SBR tokens on a 1:1 basis from the treasury in replacement of the sunSBR tokens that are currently locked on sunny.ag. This will allow us to unlock the value of the sunSBR tokens and put them to use. It is unclear why the Sunny Aggregator was abandoned by its developer. It is possible that the project may have faced technical challenges or funding issues that made it difficult to continue development. It is also possible that the developers may have shifted their focus to other projects or found the Sunny Aggregator to be no longer viable for their goals.

In order to ensure the fairness and transparency of this proposal, I suggest the following steps:

1. The sunSBR tokens locked in a smart contract and their ownership will be transferred to the DAO.

2. The DAO will then issue SBR tokens on a 1:1 basis to the holders of the locked sunSBR tokens.

3. The newly issued SBR tokens will be transferrable and can be used by the holders.

I believe this proposal will benefit the users by unlocking the value of the sunSBR tokens and allowing them to be put to use within the ecosystem. I look forward to discussing this proposal further with the members of the DAO.

**Comment by macalinao** [comment]
I voted abstain here.

The way I think we would implement this in the easiest way is to use Openbook to buy sunSBR for SBR. We can have a limit order of whatever the total outstanding sunSBR is.

The disadvantage to this is that some griefer could theoretically mint more sunSBR to prevent full redemption of sunSBR, but we can cross that bridge when we get there.

**Comment by aperire** [comment]
Can we use SBR as quote token on OpenBook? Let us know if detailed execution plan is ready.

**Comment by rewdstar** [comment]
@macalinao afaik new sunSBR minting has been disabled for quite a while. 

So looks like there is no concern left. Wonder if you have started proceeding with the Openbook plan in the background or still waiting for some things?

**Comment by tmnxeq** [comment]
@macalinao the proposal passed on 14 dec

wen update?

![2022-12-27_18-48-01_Brave Browser_Saber Proposal #43 Issue 1 SBR each for sunSBR  Saber](https://user-images.githubusercontent.com/101520234/209709547-d753c938-003f-42d8-b32b-28dafd406eeb.png)

**Comment by macalinao** [comment]
Passed
