### ISSUE TITLE
[PROPOSAL] Dev Ops Budget

### ISSUE THREAD

**Issue by c2yptic** [saber-hq/governance#26]
## Summary

- Issue a budget of $25,000 for dev grants to update the frontend and backend of the Saber app. If approved, the project should be done in approx. 2 months. 

## Motivation

- The front end needs an update and some of the backend aka infra, needs to be updated as well to be fully up to date with all new Solana features. This serves as a great opportunity for the DAO to take more lead in the development of Saber in the new SaberDAO chapter.
- I've found 2 talented developers for FE and BE respectively (Rockooor and dev4all AKA Keisuke) that will be able to start working on this project immediately if the proposal passes.

## Actions

- Allocate $25,000 from the treasury that will be used to pay for developers to update the FE- and BE.
- Overview of scope of FE- and BE dev work https://hackmd.io/@rockooor/SkIOQzwBT  

## Expectations/impact

- Greatly improve UX and UI for both LPs, swappers, and DAO - participants
- Set a solid foundation for future app updates both FE- and BE-wise
- Shows to the broader Solana Ecosystem that the SaberDAO revamp is alive and kicking

**Comment by omgbbqhaxx** [comment]
How we can see total budget of saber dao?

**Comment by c2yptic** [comment]
Hey @omgbbqhaxx ! The DAO treasury can be found here (excluding addys with trading and LP withdrawal fees from 2023)  

https://solscan.io/account/H9XuKqszWYirDmXDQ12TZXGtxqUYYn4oi7FKzAm7RHGc

**Comment by Mykyta-Metolkin** [comment]
Hey, what's the current active discord link?
Don't see any activity on socials

**Comment by c2yptic** [comment]
> Hey, what's the current active discord link? Don't see any activity on socials

[discord.gg/cmVUgRXS53](https://t.co/39X7vDabpE)

https://twitter.com/The_Saber_DAO

**Comment by c2yptic** [comment]
Passed: https://tribeca.so/gov/sbr/proposals/51

Funds will be sent to: H6SjJMKV2wL19AUYT5SYUq8UGvQ5mnmz7tkjgF2MuXRo
