### ISSUE TITLE
[PROPOSAL] SBR LP Fees Revamp

### ISSUE THREAD

**Issue by c2yptic** [saber-hq/governance#28]
_This proposal was brought forth by **icebeaver** in the in-discord DAO forum_

## Summary 

icebeaver suggest that the DAO consider changing the weights for LP fees distribution to 1:1 ratio between the LP providers and veSBR holders setting the LP fees to the following parameters given the Trade fee:

Total fee =  [Fee allocation to LP providers] * 0.5 + [Fee allocation to veSBR holders] * 0.5

This being said, the current 0.01% fee applicable to most pools (with exclusion to USDH-USDC LP) after the revamp would look as follows: 0.005% attributable to LP Providers, 0.005% attributable to veSBR holders.

## Motivation

Several major outcomes could be underlined from that change: 
- SaberDAO will receive a constant inflow of funds for its growth and stakeholder's compensation proportional to its trading volume; 
Example:
According to Dune dashboard (ref. https://dune.com/0xpibs/saberdao), 24h cumulative volume on Saber is $6,322,402 as of 08.01.2024. Given this number, Implied annualized volume would result in approx. $2,307,676,730 generating $230,767.6 worth of profits. I will use this number further on for illustrative purpuses. If the proposal gets approved, SaberDAO will receive $115,383 of inflows given the volume persists at a constant.
 
- This would result in a healthier tokenomics for the protocol since LP providers are incentivized with SBR allocation, therefore their SBR allocation could be staked maximizing performance for LP providers and creating value for veSBR holders, as a consequence the proportion of SBR tokens staked would likely increase as well.

- Moreover, this change is aligned with the Vote-Markets protocol (hereinafter, VMP) proposal in a way that VMP participants would be financially incentivized to maximize their stake of veSBR.

- As a downside, LP Providers would be affected due to lower fees earned.
However, the current state of SBR token emissions looks as the following: 1,000,000.0 SBR is emitted per day, meaning 365,000,000.0 SBR token emissions per year, hence the current dilution rate is 16.38% which greatly exceeds the protocol's implied profit margins attributable to veSBR token holders ROE[veSBR] = 115,383.8/(11,954,688.95-4,099,917.6) = 1.46%. In the end, this means that LP providers are receiving a share of fee-accruing token that would benefit every participant in the long run.

Current number of staked tokens is relatively low, having only 771,389,852/2,229,903,029 = 34.59% of the total supply being staked. Fee redistributions would incentivize DAO participance.

## Actions

Changing the weights for LP fees distribution to 1:1 ratio between the LP providers and veSBR holders setting the LP fees to the following parameters given the Trade fee:

Total fee =  [Fee allocation to LP providers] * 0.5 + [Fee allocation to veSBR holders] * 0.5

This being said, the current 0.01% fee applicable to most pools (with exclusion to USDH-USDC LP) after the revamp would look as follows: 0.005% attributable to LP Providers, 0.005% attributable to veSBR holders.

**Comment by c2yptic** [comment]
Proposal passed: https://tribeca.so/gov/sbr/proposals/59

**Comment by axelcazorla** [comment]
hello posible vote??
