### ISSUE TITLE
[PROPOSAL] Audit Budget proposal

### ISSUE THREAD

**Issue by c2yptic** [saber-hq/governance#33]
## Summary

Several updates are being worked on (such as the front end and back end upates), and more are soon to be worked on, including smart contract and other protocol updates that need to be audited so that we can be proactive regarding user and protocol security.

We want to allocate a budget specifically for Audits. The budget will cover more than 1 audit, and is a good start. 

## Motivation

We need to make sure that we prioritize security. With the FE & BE update and future improvements of the protocol, including Tribeca updates and full treasury deployment, we should and need to audit everything. Safety first! 

Expectations:
- Improve the security and trust in Saber
- Comfortably work with the treasury on-chain
- Show the DAO and the Solana ecosystem, that the DAO and its leadership takes security seriously.
- The DAO can work with security in a proactive manner.

## Actions

Allocate $50,000 from the SaberDAO treasury for Audits.

**Comment by c2yptic** [comment]
Proposal passed: https://tribeca.so/gov/sbr/proposals/55

Funds will be sent to: H6SjJMKV2wL19AUYT5SYUq8UGvQ5mnmz7tkjgF2MuXRo

**Comment by VikVM** [comment]
Hey @c2yptic what firms are in the short-list?
