### ISSUE TITLE
[PROPOSAL] Pay for RPC expenses from DAO to Triton.one for Nov 2022-Nov 2023

### ISSUE THREAD

**Issue by macalinao** [saber-hq/governance#9]
## Summary

Pay up to $6000 USDC over the next 12 months to EGboznfwLbc95DtSEhLVxZ53uH6thgpsqr3LC3oJptTf for RPC-related expenses

## Motivation

RPC nodes are important for Saber, Tribeca, and related services to function.

## Actions

Send 500 USDC to EGboznfwLbc95DtSEhLVxZ53uH6thgpsqr3LC3oJptTf from the DAO treasury, once per month. This month, send 1000 USDC to cover November and December costs.

**Comment by brianlong** [comment]
Thanks for the opportunity to provide RPC services to Saber. We'll work hard to make your app more awesome.

**Comment by macalinao** [comment]
Passed and executed.
